version: 2.1
executors:
  java17:
    docker:
    - image: 'cimg/openjdk:17.0'
orbs:
  maven: circleci/maven@1.4.1
workflows:
  maven_clean_test:
    jobs:
      - maven/clean/test:
          command: 'clean test'
          executor: java17