version: 2.1

java17:
  docker:
    - image: 'cimg/openjdk:17.0'

orbs:
  maven: circleci/maven@1.4.1

workflows:
    maven_test:
      jobs:
        - maven/test:
            command: '-X verify'
#            executor: java17