version: 2.1
executors:
  java17:
    docker:
    - image: 'cimg/openjdk:17.0'
orbs:
  maven: circleci/maven@1.4.1
workflows:
  #  maven_clean:
  #    jobs:
  #      - maven/clean:
  #          command: '- X clean'
  #          executor: java17
  maven_clean_test:
    jobs:
      - maven/clean:
          command: 'clean'
          executor: java17
      - maven/test:
          command: 'test'
          executor: java17
          requires:
            - maven/clean